apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "qm-proxy-service.fullname" . }}
spec:
  dnsNames:
  - {{ .Values.ingress.dnsName }}
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  secretName: {{ .Values.ingress.secretName }}